### ISSUE TITLE
Handling different FHIR versions

### ISSUE THREAD

**Issue by aschuler84** [HL7Austria/HL7-AT-FHIR-Core-STU3#32]
**Real Submitter**
@aschuler84 

**Resource(s)/Profiles incl. Version**
all

**Links**
https://github.com/HL7Austria/hl7-at-fhir-profiles

**Priority**
Major 

**Is your feature request related to a problem? Please describe.**
In order to properly support different versions of FHIR for our Austrian profiles, we need to define how to deal with different profile versions and what approach branching, tagging, etc. we apply.  

**Describe the solution you'd like**
In the future, there might be different versions for the same profiles available. Therefore we need to define how to properly handle such situations. Therefore, I suggest 
- a) an additional section in the contribution.md
- b) apply changes to the repository structure as needed.

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by oliver-krauss** [comment]
Considering how the development is working in other countries I'd add
c) having separate repositories for each version, and linking between different sub-pages on the rendered content like how the fhir spec itself is doing.

**Comment by regelkraut** [comment]
Discussed on TC FHIR Call on 15.10.2020:
**Motion:** 
Introduce new structure for repositories for the https://github.com/HL7Austria project:
* For every FHIR versio a new repository is created 
* The repositories a distinguished between HL7 Austria FHIR Core profiles and specific IG projects
* The old repository "hl7-at-fhir-profiles" will be resolved in the new repository for STU3
* The naming convention is the following: HL7-AT-FHIR-[ProjectPart]-[FHIR-Version], e.g.:
* HL7-AT-FHIR-Core-STU3 (ex hl7-at-fhir-profiles repo)
* HL7-AT-FHIR-Core-R4
* HL7-AT-FHIR-Core-R5
* HL7-AT-FHIR-IG-Laborbefund-R4

**Change Type:** Compatible-substantive
**Resolution: final resolution:** Persuasive with mod
**Mover/Seconder: For-Against-Abstain:** Martin Asenbaum/Nikola Tanjga: 7-0-0
**_Motion passed!_**
